### ISSUE TITLE
Update mod to support Better Azalea being merged with Ecologics

### ISSUE THREAD

**Issue by Peach774** [onVoid/Macaws-Bridges-Azalea#1]
Ecologics absorbed better azalea so the mod needs to be updated to support that

**Comment by brnbrd** [comment]
Yes, this mod is now discontinued because of the ecologics changes. ideally, with ecologics’ upcoming compat update, they will officially support macaws bridges. otherwise, i may make another mod to provide that

**Comment by brnbrd** [comment]
I have submitted a pull request containing full optional support to the Ecologics repository. If they choose to accept it, then support will officially be within the base mod. This mod is discontinued. Thanks.
